### ISSUE TITLE
Can't scroll friend list & reversed button functions

### ISSUE THREAD

**Issue by HayanShiro** [MathewSachin/Fate-Grand-Automata#446]
Before opening an issue:
- [O] I tested the latest release
- [O] I looked at other issues (even the closed ones)
- [O] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [O] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
1) when I use the battle, it doesn't scroll through the friends list and it doesn't click the support. like it doesn't even recognize the supports screen. 
2) next battle and next turn buttons of the command maker is reversed and does the other button's functions. 

**Screenshots**
![Screenshot_20200920-204834_FateGO](https://user-images.githubusercontent.com/39473180/93710593-e2f13400-fb82-11ea-9587-50139536462b.jpg)

**Video**

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S20+
 - Screen size: 6.7 inch
 - Android Version: Android 10
 - RAM: 12GB

**Comment by HayanShiro** [comment]
https://youtu.be/iqSYz4u2NkU

**Comment by MathewSachin** [comment]
Hey, is the `Ignore notch calculation` option ON by any chance? If so, you have to turn it OFF for your phone.
Just to confirm, you've made FGA full-screen too, right? (I can see that FGO is full-screen).

For the second bug, @ScathachSkadi @sleeping-player, can you check if there was a mistake in translation?

**Comment by ScathachSkadi** [comment]
I think he has to turn off the notch settings. And I don't think there is a translation mistake on auto skill.

**Comment by sleeping-player** [comment]
![Screenshot_20200920-211216.png](https://user-images.githubusercontent.com/69798206/93711065-079adb00-fb86-11ea-860f-eb379596641c.png)
Yes this is ignore notch misconfiguration.

**Comment by ScathachSkadi** [comment]
I double checked to see if there is something wrong with the translation, but it's hard to make a mistake here. There's barely anything to translate on auto skill command. If there was a mistake, then I would have been corrected by a lot of people on the korean community. Judging by the black bars, yes turn off notch calculation.

**Comment by HayanShiro** [comment]
I've turned off notch calculations but it still doesn't seem to recognize the supports. I'll record it again tomorrow and post it here. Thank you for help ^^

I'll detail the 2nd bug tomorrow as well.

**Comment by sleeping-player** [comment]
> I double checked to see if there is something wrong with the translation, but it's hard to make a mistake here. There's barely anything to translate on auto skill command. If there was a mistake, then I would have been corrected by a lot of people on the korean community. Judging by the black bars, yes turn off notch calculation.

This is correct. Unfortunately, as I am not good at dealing with facecards, I mainly use NP for autoskill, but the Korean community seems to use facecards well, which cannot be achieved if the terminology is wrong.

**Comment by ScathachSkadi** [comment]
Well, I guess we need more detail about this issue.

**Comment by mattmcheng** [comment]
I'm having this exact issue on Galaxy S10+
Battle works fine, just doesn't seem to recognize that it is on the support screen. I've tried changing support settings, notch calculation on / off, etc. The add support image script mode works though. It knows that it is support screen and reads them correctly.

**Comment by HayanShiro** [comment]
I've tested the app today and turning off notch calculations made it read supports correctly. Thank you Matthew and Scathach. 

Detail about the 2nd bug: when I use the "next battle>>" it doesn't recognize when 2nd battle starts (it uses normal command cards instead of set autoskill properties) but when I use "next turn" it recognizes the next battle and uses the set autoskill properties.

**Comment by reconman** [comment]
2nd bug: lower the stage similarity % in fine tuning, try 70-75

**Comment by HayanShiro** [comment]
^That solved it and also the issue of not activating np even when it's set to do it. Thanks reconman.
